import { MoneroDaemonConfig } from './monero-api.interface';
import { MoneroRpc } from './monero-rpc';

export interface MoneroWalletRpcConfig extends MoneroDaemonConfig {}

export interface CheckTxProofParams {
  txid: string;
  address: string;
  signature: string;
  message?: string;
}

export interface CheckTxProofResult {
  confirmations: number;
  good: boolean;
  in_pool: boolean;
  received: number;
}

interface JsonRpcTransport {
  jsonRpc<T>(method: string, params?: Record<string, unknown>): Promise<T>;
}

/**
 * Minimal monero-wallet-rpc adapter for public proof verification.
 *
 * `check_tx_proof` lives on wallet RPC, not monerod. It only receives
 * shareable proof material: txid, destination address, optional message,
 * and the signature generated by the sender's wallet.
 */
export class MoneroWalletRpc {
  private rpc: JsonRpcTransport;

  constructor(config: MoneroWalletRpcConfig);
  constructor(rpc: JsonRpcTransport);
  constructor(configOrRpc: MoneroWalletRpcConfig | JsonRpcTransport) {
    this.rpc = typeof (configOrRpc as JsonRpcTransport).jsonRpc === 'function'
      ? configOrRpc as JsonRpcTransport
      : new MoneroRpc(configOrRpc as MoneroWalletRpcConfig);
  }

  public async checkTxProof(params: CheckTxProofParams): Promise<CheckTxProofResult> {
    return this.rpc.jsonRpc<CheckTxProofResult>('check_tx_proof', {
      txid: params.txid,
      address: params.address,
      signature: params.signature,
      ...(params.message ? { message: params.message } : {}),
    });
  }
}

export function moneroWalletRpcFromEnv(): MoneroWalletRpc | null {
  const rpcUrl = process.env.MONERO_WALLET_RPC_URL ?? process.env.XMR_WALLET_RPC_URL;
  if (!rpcUrl) {
    return null;
  }
  return new MoneroWalletRpc({
    rpcUrl,
    rpcUser: process.env.MONERO_WALLET_RPC_USER ?? process.env.XMR_WALLET_RPC_USER,
    rpcPassword: process.env.MONERO_WALLET_RPC_PASSWORD ?? process.env.XMR_WALLET_RPC_PASSWORD,
    timeoutMs: Number(process.env.MONERO_WALLET_RPC_TIMEOUT_MS ?? process.env.XMR_WALLET_RPC_TIMEOUT_MS ?? 10_000),
  });
}
